version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 280390769856.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t myrepo .
      - docker tag myrepo/MAVEN:latest 280390769856.dkr.ecr.ap-south-1.amazonaws.com/myrepo:latest
      - docker push 280390769856.dkr.ecr.ap-south-1.amazonaws.com/myrepo:latest
