version: 0.2

phases:
 install: 
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    runtime-versions:
         docker: 19
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 280390769856.dkr.ecr.ap-south-1.amazonaws.com      
  build:
    commands:
      - docker build -t myrepo/maven .
      - docker tag myrepo/MAVEN:latest 280390769856.dkr.ecr.ap-south-1.amazonaws.com/myrepo/maven:latest
      - docker push 280390769856.dkr.ecr.ap-south-1.amazonaws.com/myrepo/maven:latest
