version: 0.2

phases:
  install:
    runtime-versions:
         docker: 18
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 280390769856.dkr.ecr.ap-south-1.amazonaws.com      
  build:
    commands:
      - docker build -t myrepo/MAVEN .
      - docker tag myrepo/MAVEN:latest 280390769856.dkr.ecr.ap-south-1.amazonaws.com/myrepo/MAVEN:latest
      - docker push 280390769856.dkr.ecr.ap-south-1.amazonaws.com/myrepo/MAVEN:latest
